repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.32.0  # Use the latest stable release tag
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
      - id: talisman-push
